name: Default Context variables printing
on: 
  workflow_dispatch
env:
  Author: td@try-devops.xyz
jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "environment variables priting"
        run: |
          echo "Hard coded env variable is: ${{ env.Author }}"
      - name: "Checking context variables"
        run: |
          echo "Repository name: ${{ github.repository }}"
          echo "Workflow name: ${{ github.workflow }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "GitHub ref: ${{ github.ref }}"
          echo "GraphQL URL: ${{ github.graphql_url }}"
          echo "Github repo: ${{ github.repository }}"
          echo "Github workspace: ${{ github.workspace }}"
          echo "Github server URL: ${{ github.server_url }}"
          echo "Repository owner name is: ${{ github.repository_owner }}"
          echo "GitHub repository id is: ${{ github.repository_id }}"
          echo "GitHub retention days: ${{ github.retention_days }}"
