name: Testing Context variables
on: 
  workflow_dispatch
env:
  Author: td@try-devops.xyz
jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking context variables"
        run: |
          echo "Repository name: ${{ github.repository }}"
          echo "Workflow name: ${{ github.workflow }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "GitHub ref: ${{ github.ref }}"
          echo "Action path: ${{ github.action_path }}"
          echo "Action repository: ${{ github.action_repository }}"
          echo "Action status: ${{ github.action_status }}"
          echo "GraphQL URL: ${{ github.graphql_url }}"
          echo "Github repo: ${{ github.repository }}"
          echo "Github workspace: ${{ github.workspace }}"
          echo "Github server URL: ${{ github.server_url }}"
          echo "Repository owner name is: ${{ github.repository_owner }}"
