name: self-hosted-runner
# on:
#   # push:
#   #   branches: 
#   #     - master
#   # pull_request:
#   #   branches: 
#   #     - master
on:
  workflow_dispatch:
env:
  Date: "25/03/2025"
  Author: "td@try-devops.xyz"
  Project: "TFPROJECT"
  GITREPO: "https://github.com/thangacodes/terraform_usecases.git"
jobs:
  build:
    runs-on: ubuntu-latest  # Use the label of your self-hosted runner
    steps:
    - name: Setup custom directory
      run: |
        pwd
        git clone ${{ env.GITREPO }}
    - name: Execute custom init script
      run: |
        echo "checking the path"
        pwd
        ls -la
        sh simple.sh

