name: AWS Infrastructure Provisioning using IaC (Terraform)
# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch
env:
  Author: Td@try-devops.xyz
  corp: try-devops.xyz
  primary_cloud: aws-cloud
  secondary_cloud: azure-cloud
  additional_cloud: VMware-cloud
jobs:
  terraform_execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: "About your employer: ${{ env.corp }}"
        run: |
          echo "The Author of this Git Repository is owned by:" ${{ env.Author}}
          echo "The Author is working for:" ${{ env.corp }}
          echo "Company ${{ env.corp }} is use primary cloud as:" ${{ env.primary_cloud }}
          echo "Company ${{ env.corp }} is use secondary cloud as:" ${{ env.secondary_cloud }}
          echo "Company ${{ env.corp }} is use additional cloud as:" ${{ env.additional_cloud }}
          sleep 2
          pwd
      - name: "Change to the directory and run the shell script"
        run: |
          pwd
          echo "Listing the files in $(pwd)"
          ls -la
          cd aws_terraform/conditional_based_ec2_creation
          ls -l
          echo "Running the shell script"
          sh simple.sh
          
