name: AWS Infra Delivery Using IaC (Terraform)
# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch
env:
  Author: admin@try-devops.xyz
  corp: try-devops.xyz
  primary_cloud: AWS Cloud
  secondary_cloud: AZURE Cloud
  additional_cloud: VMWARE Cloud
  script_path: aws_terraform/conditional_based_ec2_creation
  shell_exec: sh simple.sh
jobs:
  env_variable_checking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: "About Employer: ${{ env.corp }}"
        run: |
          echo "The Author of this Git Repository is owned by:" ${{ env.Author}}
          echo "The Author is working for:" ${{ env.corp }}
          echo "Company ${{ env.corp }} is using PRIMARY CLOUD as:" ${{ env.primary_cloud }}
          echo "Company ${{ env.corp }} is using SECONDARY CLOUD as:" ${{ env.secondary_cloud }}
          echo "Company ${{ env.corp }} is using ADDITIONAL CLOUD as:" ${{ env.additional_cloud }}
  tf_execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Change to the directory and run the shell script"
        run: |
          echo "Listing the files in the current directory: $(pwd)"
          cd ${{ env.script_path }}  # Change to the specified directory
          echo "Current directory: $(pwd)"
          echo "Running the shell script"
          ${{ env.shell_exec }}  
          
